### PR TITLE
Update to 1.21.4 PR

### PR DESCRIPTION
**Pull request by lowercasebtw**
Some things need fixing like the MAIN_TARGET and the sky rotating with camera movement

Also this should support 1.21.2 also, but I think I may have set the version range to 1.21.3+ so you can fix that if you want

### CODE REVIEW

**Comment by lowercasebtw** [comment]
And MixinFogRenderer too, I forgot. Some of the mixins in it need fixing, currently commented out.

**Comment by Nilsson321** [comment]
ETA?

**Comment by lowercasebtw** [comment]
no eta, when amere comes back

**Comment by lowercasebtw** [comment]
oops i typed fox instead of fog

**Comment by lowercasebtw** [comment]
Alright, seems good enough to be merged/released :)

**Comment by lowercasebtw** [comment]
nvm seems the fog is still broken when nuit is "disabled" with the ingame toggle, might be another missing check somewhere in the fogrenderer

**Comment by jackpurrin** [comment]
How do I compile the project so I can use it?

**Comment by Johnsmith927** [comment]
can you run an action/workflow so we can download the artifact? idk how else to get the .jar from the pr

**Comment by lowercasebtw** [comment]
i uploaded the 1.21.2/3/4 builds in the discord server

**Comment by ghost** [comment]
got a link to the discord server?

**Comment by Johnsmith927** [comment]
> got a link to the discord server?

It’s in the ReadMe: https://discord.gg/quvzkaV

**Pull request merged**
