### PR TITLE
Initial 1.18.2 update

### PR DESCRIPTION
**Pull request by FlashyReese**
This pull request updates FabricSkyboxes to 1.18.2. It also implements vanilla behavior to prevent the skybox rendering in certain conditions like being submerged in lava/powdered snow or having the blindness effect,

Some limited testing has been done using the Fancy Skies resource pack.

### CODE REVIEW

**Review by AMereBagatelle — APPROVED** [review]
Looks good, merging after conflicts are resolved (I'll deal with them)

**Comment by Marcelo20XX** [comment]
So this mean it will not render underwater?

**Comment by FlashyReese** [comment]
> So this mean it will not render underwater?

Only the above mentioned conditions, it will still render the sky box under water.

**Comment by AMereBagatelle** [comment]
I tested, and #31 is still present, so it's not fixed yet.

**Pull request merged**
